version: "3.9"

services:
  django:
    container_name: django
    build: ./aminoreader_project
    #image: python/python:3.9-buster
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./aminoreader_project:/usr/src/aminoreader_project
    ports:
      - 8000:8000
